name: Publish Package to GitHub Packages

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish (leave empty to use package.json version)"
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://npm.pkg.github.com"
          scope: "@brightidea"

      - name: Install dependencies
        run: npm install

      - name: Debug - Show package.json build script
        run: cat package.json | grep -A 3 '"build"'

      - name: Debug - Check if rollup-plugin-postcss is installed
        run: npm list rollup-plugin-postcss || echo "rollup-plugin-postcss not found (good)"

      - name: Debug - List all postcss config files
        run: ls -la postcss.* .postcssrc* 2>/dev/null || echo "No postcss config files found"

      - name: Remove auto-generated postcss.config.js if it exists
        run: rm -f postcss.config.js postcss.config.mjs

      - name: Build package
        run: npm run build

      - name: Update version (if manual trigger with version)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.version != ''
        run: npm version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
